name: uploadToS3

on:
  push:
    branches: [ "main" ] # Or your desired branches

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        uses: aws-actions/install-aws-cli@v2

      - name: Configure AWS Credentials 
        # (Replace with your actual credentials management method)
        uses: actions/aws-credentials@v3 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Sync to S3
        uses: aws-actions/aws-s3-sync@v1
        with:
          args: --delete 
          bucket: 'iam-ivan.com' 
          region: 'us-east-1' 
          source: ./ # Or the path to your website's root directory
          dest: . # Or the desired destination path in your S3 bucket

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2VPNM1NBU20OE \
            --paths "/*" 